# Generated by Django 3.0 on 2019-12-12 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200)),
                ('harga', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deskripsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_barang', models.CharField(max_length=255)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoapp.Barang')),
            ],
        ),
    ]
